version: '3.8'

services:
  galileo-git:
    image: gitea/gitea:latest
    container_name: galileo-git
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__ROOT_URL=http://localhost:3000/
      - GITEA__server__HTTP_PORT=3000
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__admin__USER=galileo_user
      - GITEA__admin__PASSWD=Galileo.12345
      - GITEA__admin__EMAIL=galileo_user@example.com
    ports:
      - "3188:3000"
    networks:
      - galileo-network-v1.1
    volumes:
      - gitea_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  repo-setup:
    image: curlimages/curl:latest
    depends_on:
      galileo-git:
        condition: service_healthy
    networks:
      - galileo-network-v1.1
    volumes:
      - ./my-files:/repo-files
    entrypoint: >
      /bin/sh -c "
      sleep 20 && \
      REPO_EXISTS=$(curl -s -o /dev/null -w \"%{http_code}\" -u galileo_user:Galileo.12345 \
      http://galileo-git:3000/api/v1/repos/galileo_user/galileo-config) && \
      if [ \"$REPO_EXISTS\" -eq 404 ]; then \
        echo 'Creating repository galileo-config...' && \
        curl -X POST \"http://galileo_user:Galileo.12345@galileo-git:3000/api/v1/user/repos\" \
             -H \"Content-Type: application/json\" \
             -d '{\"name\": \"galileo-config\", \"private\": false, \"default_branch\": \"main\"}' && \
        git clone http://galileo_user:Galileo.12345@galileo-git:3000/galileo_user/galileo-config.git && \
        cd galileo-config && \
        cp -r /repo-files/* . && \
        git add . && \
        git commit -m 'Initial commit' && \
        git push; \
      else \
        echo 'Repository galileo-config already exists, skipping creation.'; \
      fi"
    restart: "no"

volumes:
  gitea_data:

networks:
  galileo-network-v1.1:
    external: true