services:
  galileo-gitlab:
    image: galileo/gitea:1.22
    container_name: galileo-gitlab
    environment:
      - USER=git
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__RUN_MODE=prod
      - GITEA__RUN_USER=git
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__SSH_DOMAIN=localhost
      - GITEA__server__ROOT_URL=http://localhost:1880/
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__server__HTTP_PORT=80
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__SECRET_KEY=euHQvDSgdlhv3FcccsnSiDCc6d1nyu6oVXDnKO4wmDDfFi8xzjyEBI7UAGTKfSLw
      - GITEA__security__INTERNAL_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3MTg3NDYyMjl9.8fSkT65adVLsw9KOnKkKRke-Rxi0DlT6CLw5nRhdEq0
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=false
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
    networks:
      - galileo-network
    ports:
      - "1880:80"
      - "1222:22"
    volumes:
      - ./gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/v1/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  servicio-config-server:
    build: ./config-server/
    image: galileo/servicio-config-server:1.1.0
    ports:
      - 8888:8888
    restart: on-failure
    container_name: servicio-config-server
    networks:
      - galileo-network

  servicio-eureka-server:
    build: ./eureka-server/
    image: galileo/servicio-eureka-server:1.1.0
    ports:
      - 8761:8761
    restart: on-failure
    container_name: servicio-eureka-server
    networks:
      - galileo-network
    
  servicio-usuarios:
    build: ./usuarios/
    image: galileo/servicio-usuarios:1.1.0
    restart: on-failure
    container_name: servicio-usuarios
    networks:
      - galileo-network

  servicio-oauth:
    build: ./oauth2/
    image: galileo/servicio-oauth:1.1.0
    restart: on-failure
    container_name: servicio-oauth
    ports:
      - 9100:9100
    networks:
      - galileo-network

  servicio-unidades-usuarios:
    build: ./unidadesusuarios/
    image: galileo/servicio-unidades-usuarios:1.1.0
    restart: unless-stopped
    container_name: servicio-unidades-usuarios
    networks:
      - galileo-network

  servicio-balizas:
    build: ./balizas/
    image: galileo/servicio-balizas:1.1.0
    restart: on-failure
    container_name: servicio-balizas
    networks:
      - galileo-network

  servicio-objetivos:
    build: ./objetivos/
    image: galileo/servicio-objetivos:1.1.0
    restart: on-failure
    container_name: servicio-objetivos
    networks:
      - galileo-network

  servicio-operaciones:
    build: ./operaciones/
    image: galileo/servicio-operaciones:1.1.0
    restart: on-failure
    container_name: servicio-operaciones
    networks:
      - galileo-network

  servicio-conexiones:
    build: ./conexiones/
    image: galileo/servicio-conexiones:1.1.0
    restart: on-failure
    container_name: servicio-conexiones
    networks:
      - galileo-network

  servicio-apis:
    build: ./apis/
    image: galileo/servicio-apis:1.1.0
    restart: on-failure
    container_name: servicio-apis
    networks:
      - galileo-network

  servicio-unidades:
    build: ./unidades/
    image: galileo/servicio-unidades:1.1.0
    restart: on-failure
    container_name: servicio-unidades
    networks:
      - galileo-network

  servicio-importador:
    build: ./importador/
    image: galileo/servicio-importador:1.1.0
    restart: on-failure
    container_name: servicio-importador
    networks:
      - galileo-network

  servicio-geocercas:
    build: ./geocercas/
    image: galileo/servicio-geocercas:1.1.0
    restart: on-failure
    container_name: servicio-geocercas
    networks:
      - galileo-network

  servicio-evidencias:
    build: ./evidencias/
    image: galileo/servicio-evidencias:1.1.0
    restart: on-failure
    container_name: servicio-evidencias
    networks:
      - galileo-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  servicio-empleos:
    # build: ./empleos/
    image: galileo/servicio-empleos:1.1.0
    restart: on-failure
    container_name: servicio-empleos
    networks:
      - galileo-network

  servicio-datosbalizas:
    #build: ./datosbalizas/
    image: galileo/servicio-datosbalizas:1.1.0
    restart: on-failure
    container_name: servicio-datosbalizas
    networks:
      - galileo-network

  servicio-estados:
    #build: ./estados/
    image: galileo/servicio-estados:1.1.0
    restart: on-failure
    container_name: servicio-estados
    networks:
      - galileo-network

  servicio-perfiles:
    #build: ./perfiles/
    image: galileo/servicio-perfiles:1.1.0
    restart: on-failure
    container_name: servicio-perfiles
    networks:
      - galileo-network

  servicio-permisos:
    #build: ./permisos/
    image: galileo/servicio-permisos:1.1.0
    restart: on-failure
    container_name: servicio-permisos
    networks:
      - galileo-network

  servicio-provincias:
    #build: ./provincias/
    image: galileo/servicio-provincias:1.1.0
    restart: on-failure
    container_name: servicio-provincias
    networks:
      - galileo-network

  servicio-tipobalizas:
    #build: ./tipobalizas/
    image: galileo/servicio-tipobalizas:1.1.0
    restart: on-failure
    container_name: servicio-tipobalizas
    networks:
      - galileo-network

  servicio-historicoobjetivosbalizas:
    #build: ./historicoobjetivosbalizas/
    image: galileo/servicio-historicoobjetivosbalizas:1.1.0
    restart: on-failure
    container_name: servicio-historicoobjetivosbalizas
    networks:
      - galileo-network

  servicio-juzgados:
    #build: ./juzgados/
    image: galileo/servicio-juzgados:1.1.0
    restart: on-failure
    container_name: servicio-juzgados
    networks:
      - galileo-network

  servicio-tipocontratos:
    #build: ./tipocontratos/
    image: galileo/servicio-tipocontratos:1.1.0
    restart: on-failure
    container_name: servicio-tipocontratos
    networks:
      - galileo-network

  servicio-gateway-server:
    #build: ./gateway/
    image: galileo/servicio-gateway-server:1.1.0
    ports:
      - 8090:8090
    restart: on-failure
    container_name: servicio-gateway-server
    networks:
      - galileo-network
        #volumes:
        #    - /home/countigo/galileo-artifacts/gateway-server.jar:/gateway-server.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server
        #- servicio-usuarios
        #- servicio-oauth
        #- servicio-unidades

  servicio-trazabilidad:
    #build: ./trazabilidad/
    image: galileo/servicio-trazabilidad:1.1.0
    restart: on-failure
    container_name: servicio-trazabilidad
    networks:
      - galileo-network

  # gitlab1:
  #   image: gitlab/gitlab-ce:latest
  #   restart: always
  #   container_name: galileo-gitlab-config1
  #   networks:
  #     - galileo-network
  #   ports:
  #     - "1880:80"
  #     - "1443:443"
  #     - "1222:22"
  #   volumes:
  #     - /srv/gitlab-galileo-config-1/config:/etc/gitlab
  #     - /srv/gitlab-galileo-config-1/logs:/var/log/gitlab
  #     - /srv/gitlab-galileo-config-1/data:/var/opt/gitlab

  # bd:
  #   image: mysql:latest
  #   restart: on-failure
  #   container_name: galileo_bd
  #   command: --default-authentication-plugin=mysql_native_password --max_connections=20000
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=76xNPTa2022
  #     - MYSQL_DATABASE=galileo_bd
  #     - MYSQL_USER=galileo_bd
  #     - MYSQL_PASSWORD=xD9MbjJLesUId4QX
  #   volumes:
  #     - ./data:/var/lib/mysql
  #     - ./bd:/docker-entrypoint-initdb.d
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - galileo-network

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   restart: on-failure
  #   ports:
  #     - 8585:80
  #   environment:
  #     - PMA_HOST=bd
  #     - MYSQL_ROOT_PASSWORD=76xNPTa2022
  #   networks:
  #     - galileo-network

  web-build:
    image: node:14
    volumes:
      - ./web/galileo_servicio_web:/app
    working_dir: /app
    networks:
      - galileo-network
    command: >
      bash -c "rm -f /app/build_complete &&
              npm install -g @angular/cli &&
              npm install &&
              npm run build --prod &&
              touch build_complete"
    healthcheck:
      test: ["CMD", "test", "-f", "/app/build_complete"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    restart: 'no'

  # servicio-web:
  #   image: nginx:alpine
  #   volumes:
  #     - ./web/galileo_servicio_web/nginx.conf:/etc/nginx/nginx.conf
  #     - ./web/galileo_servicio_web/dist/galileo-frontend:/usr/share/nginx/html
  #     - ./web/galileo_servicio_web:/app  # Para acceder a 'build_complete'
  #   depends_on:
  #     - web-build
  #   ports:
  #     - "8079:8079"
  #   networks:
  #     - galileo-network
    # command: >
    #   bash -c "while [ ! -f /app/build_complete ]; do sleep 2; done; nginx -g 'daemon off;'"

  servicio-web:
    image: galileo/webapp:1.1.0
    build: ./web/galileo_servicio_web/
    depends_on:
      - web-build
    container_name: webapp
    restart: on-failure
    # volumes:
    #   - ./app/default.conf:/etc/nginx/conf.d/default.conf
    #            - ./app/code:/usr/share/nginx/html
    ports:
      - 8079:8079
    networks:
      - galileo-network

  #     app:
  #         image: galileo/galileo-webapp
  #         container_name: webapp
  #         restart: on-failure
  #         volumes:
  #             -  ./app/default.conf:/etc/nginx/conf.d/default.conf
  # #            - ./app/code:/usr/share/nginx/html
  #         ports:
  #             - 8089:80
  #         networks:
  #             - galileo-network
  apptest:
    image: galileo/galileo-webapptest
    container_name: webapptest
    restart: on-failure
    volumes:
      #          -  ./app/nginx.conf:/etc/nginx/nginx.conf
      - ./app/default.conf:/etc/nginx/conf.d/default.conf
    #            - ./app/code:/usr/share/nginx/html
    ports:
      - 8099:80
    networks:
      - galileo-network
    #networks:
    #galileo-network:
    #ipam:
    #driver: default
    #config:
    #- subnet: 10.10.0.0/24

volumes:
  gitea_data:

networks:
  galileo-network:
    external: true
    name: galileo-network
