version: "3.8"
services:
  servicio-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure
    container_name: servicio-zookeeper
    networks: galileo-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  servicio-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    restart: on-failure
    container_name: servicio-kafka
    networks: galileo-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: servicio-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  servicio-config-server:
    build: ./config-server/
    ports:
      - 8888:8888
    restart: on-failure
    container_name: servicio-config-server
    networks:
      galileo-network:
        ipv4_address: 10.10.0.5

  servicio-eureka-server:
    build: ./eureka-server/
    ports:
      - 8761:8761
    restart: on-failure
    container_name: servicio-eureka-server
    networks:
      galileo-network:
        ipv4_address: 10.10.0.6
        #depends_on:
        #- servicio-config-server
        #- bd
        #- phpmyadmin

  servicio-modelosbalizas:
    build: ./modelosbalizas/
    restart: on-failure
    container_name: servicio-modelosbalizas
    networks:
      galileo-network:
        ipv4_address: 10.10.0.40

  servicio-usuarios:
    build: ./usuarios/
    restart: on-failure
    container_name: servicio-usuarios
    networks:
      galileo-network:
        ipv4_address: 10.10.0.41
        #       volumes:
        #           - /home/countigo/galileo-artifacts/servicio-usuarios.jar:/servicio-usuarios.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-empleos:
    build: ./empleos/
    restart: on-failure
    container_name: servicio-empleos
    networks:
      galileo-network:
        ipv4_address: 10.10.0.42
        #volumes:
        #- /home/countigo/galileo-artifacts/servicio-empleos.jar:/servicio-empleos.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server


  servicio-balizas:
    build: ./balizas/
    restart: on-failure
    container_name: servicio-balizas
    networks:
      galileo-network:
        ipv4_address: 10.10.0.43
        #volumes:
        #    - /home/countigo/galileo-artifacts/servicio-balizas.jar:/servicio-balizas.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-conexiones:
    build: ./conexiones/
    restart: on-failure
    container_name: servicio-conexiones
    networks:
      galileo-network:
        ipv4_address: 10.10.0.44
        # volumes:
        #    - /home/countigo/galileo-artifacts/servicio-conexiones.jar:/servicio-conexiones.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-posiciones:
    build: ./posiciones/
    restart: on-failure
    container_name: servicio-posiciones
    networks:
      galileo-network:
        ipv4_address: 10.10.0.45
        #volumes:
        #- /home/countigo/galileo-artifacts/servicio-posiciones.jar:/servicio-posiciones.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-objetivos:
    build: ./objetivos/
    restart: on-failure
    container_name: servicio-objetivos
    networks:
      galileo-network:
        ipv4_address: 10.10.0.46
        # volumes:
        #    - /home/countigo/galileo-artifacts/servicio-objetivos.jar:/servicio-objetivos.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server


  servicio-datosbalizas:
    build: ./datosbalizas/
    restart: on-failure
    container_name: servicio-datosbalizas
    networks:
      galileo-network:
        ipv4_address: 10.10.0.47
        #volumes:
        #- /home/countigo/galileo-artifacts/servicio-datosbalizas.jar:/servicio-datosbalizas.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server


  servicio-estados:
    build: ./estados/
    restart: on-failure
    container_name: servicio-estados
    networks:
      galileo-network:
        ipv4_address: 10.10.0.48
        #volumes:
        #- /home/countigo/galileo-artifacts/servicio-estados.jar:/servicio-estados.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-perfiles:
    build: ./perfiles/
    restart: on-failure
    container_name: servicio-perfiles
    networks:
      galileo-network:
        ipv4_address: 10.10.0.49
        #volumes:
        #- /home/countigo/galileo-artifacts/servicio-perfiles.jar:/servicio-perfiles.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-permisos:
    build: ./permisos/
    restart: on-failure
    container_name: servicio-permisos
    networks:
      galileo-network:
        ipv4_address: 10.10.0.50
        # volumes:
        #     - /home/countigo/galileo-artifacts/servicio-permisos.jar:/servicio-permisos.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-provincias:
    build: ./provincias/
    restart: on-failure
    container_name: servicio-provincias
    networks:
      galileo-network:
        ipv4_address: 10.10.0.51
        #volumes:
        #- /home/countigo/galileo-artifacts/servicio-provincias.jar:/servicio-provincias.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-unidades:
    build: ./unidades/
    restart: on-failure
    container_name: servicio-unidades
    networks:
      galileo-network:
        ipv4_address: 10.10.0.52
        #  volumes:
        #     - /home/countigo/galileo-artifacts/servicio-unidades.jar:/servicio-unidades.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-unidades-usuarios:
    build: ./unidadesusuarios/
    restart: unless-stopped
    container_name: servicio-unidades-usuarios
    networks:
      galileo-network:
        ipv4_address: 10.10.0.53
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-importador:
    build: ./importador/
    restart: unless-stopped
    container_name: servicio-importador
    networks:
      galileo-network:
        ipv4_address: 10.10.0.54
        #volumes:
        #- /home/countigo/galileo-artifacts/servicio-importador.jar:/servicio-importador.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-operaciones:
    build: ./operaciones/
    restart: on-failure
    container_name: servicio-operaciones
    networks:
      galileo-network:
        ipv4_address: 10.10.0.55
        # volumes:
        #    - /home/countigo/galileo-artifacts/servicio-operaciones.jar:/servicio-operaciones.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-apis:
    build: ./apis/
    restart: on-failure
    container_name: servicio-apis
    networks:
      #galileo-network:
      galileo-network:
        ipv4_address: 10.10.0.56
        # volumes:
        #    - /home/countigo/galileo-artifacts/servicio-apis.jar:/servicio-apis.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server
        #- servicio-usuarios
        #- servicio-conexiones

  servicio-tipobalizas:
    build: ./tipobalizas/
    restart: on-failure
    container_name: servicio-tipobalizas
    networks:
      galileo-network:
        ipv4_address: 10.10.0.57
        #volumes:
        #    - /home/countigo/galileo-artifacts/servicio-tipobalizas.jar:/servicio-tipobalizas.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-historicoobjetivosbalizas:
    build: ./historicoobjetivosbalizas/
    restart: on-failure
    container_name: servicio-historicoobjetivosbalizas
    networks:
      galileo-network:
        ipv4_address: 10.10.0.58
        #volumes:
        #    - /home/countigo/galileo-artifacts/servicio-historicoobjetivosbalizas.jar:/servicio-historicoobjetivosbalizas.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-juzgados:
    build: ./juzgados/
    restart: on-failure
    container_name: servicio-juzgados
    networks:
      galileo-network:
        ipv4_address: 10.10.0.59
        #volumes:
        #    - /home/countigo/galileo-artifacts/servicio-juzgados.jar:/servicio-juzgados.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-tipocontratos:
    build: ./tipocontratos/
    restart: on-failure
    container_name: servicio-tipocontratos
    networks:
      galileo-network:
        ipv4_address: 10.10.0.65
        #volumes:
        #    - /home/countigo/galileo-artifacts/servicio-juzgados.jar:/servicio-juzgados.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server

  servicio-oauth:
    build: ./oauth2/
    restart: on-failure
    container_name: servicio-oauth
    ports:
      - 9100:9100
    networks:
      galileo-network:
        ipv4_address: 10.10.0.60
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server
        #- servicio-usuarios

  servicio-gateway-server:
    build: ./gateway/
    ports:
      - 8090:8090
    restart: on-failure
    container_name: servicio-gateway-server
    networks:
      galileo-network:
        ipv4_address: 10.10.0.61
        #volumes:
        #    - /home/countigo/galileo-artifacts/gateway-server.jar:/gateway-server.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server
        #- servicio-usuarios
        #- servicio-oauth
        #- servicio-unidades

  servicio-trazabilidad:
    build: ./trazabilidad/
    restart: on-failure
    container_name: servicio-trazabilidad
    networks:
      galileo-network:
        ipv4_address: 10.10.0.62
        #       volumes:
        #           - /home/countigo/galileo-artifacts/servicio-usuarios.jar:/servicio-usuarios.jar
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server
        #- servicio-usuarios
        #- servicio-oauth
        #- servicio-gateway-server

  servicio-evidencias:
    build: ./evidencias/
    restart: on-failure
    container_name: servicio-evidencias
    networks:
      galileo-network:
        ipv4_address: 10.10.0.63
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      #volumes:
      #- /home/countigo/galileo-artifacts/servicio-datosbalizas.jar:/servicio-datosbalizas.jar
      #depends_on:
      #- servicio-config-server
      #- servicio-eureka-server
      #- servicio-usuarios
      #- servicio-oauth
      #- servicio-gateway-server

  servicio-geocercas:
    build: ./geocercas/
    restart: on-failure
    container_name: servicio-geocercas
    networks:
      galileo-network:
        ipv4_address: 10.10.0.64
        #depends_on:
        #- servicio-config-server
        #- servicio-eureka-server
        #- servicio-gateway-server

        #    gitlab:
        #        image: gitlab/gitlab-ce:latest
        #        restart: always
        #        container_name: galileo-gitlab-config
        #        networks:
        ##          - galileo-network
        #          galileo-network:
        #            ipv4_address: 10.10.0.10
        #        ports:
        #           - "1880:80"
        #           - "1443:443"
        #           - "1222:22"
        #        volumes:
        #           - /srv/gitlab-galileo/config:/etc/gitlab
        #           - /srv/gitlab-galileo/logs:/var/log/gitlab
        #           - /srv/gitlab-galileo/data:/var/opt/gitlab


  gitlab1:
    image: gitlab/gitlab-ce:latest
    restart: always
    container_name: galileo-gitlab-config1
    networks:
      #          - galileo-network
      galileo-network:
        ipv4_address: 10.10.0.10
    ports:
      - "1880:80"
      - "1443:443"
      - "1222:22"
    volumes:
      - /srv/gitlab-galileo-config-1/config:/etc/gitlab
      - /srv/gitlab-galileo-config-1/logs:/var/log/gitlab
      - /srv/gitlab-galileo-config-1/data:/var/opt/gitlab

  bd:
    image: mysql:latest
    restart: on-failure
    container_name: galileo_bd
    command: --default-authentication-plugin=mysql_native_password --max_connections=20000
    environment:
      - MYSQL_ROOT_PASSWORD=76xNPTa2022
      - MYSQL_DATABASE=galileo_bd
      - MYSQL_USER=galileo_bd
      - MYSQL_PASSWORD=xD9MbjJLesUId4QX
    volumes:
      - ./data:/var/lib/mysql
      - ./bd:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      #            - galileo-network 
      galileo-network:
        ipv4_address: 10.10.0.3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    ports:
      - 8585:80
    environment:
      - PMA_HOST=bd
      - MYSQL_ROOT_PASSWORD=76xNPTa2022
    networks:
      galileo-network:
        ipv4_address: 10.10.0.80

  servicio-web:
    #image: galileo/servicio-web
    build: ./web/galileo_servicio_web/
    container_name: servicio-web
    restart: on-failure
    # volumes:
    #   - ./app/default.conf:/etc/nginx/conf.d/default.conf
    #            - ./app/code:/usr/share/nginx/html
    ports:
      - 8079:8079
    networks:
      - galileo-network

  #     app:
  #         image: galileo/galileo-webapp
  #         container_name: webapp
  #         restart: on-failure
  #         volumes:
  #             -  ./app/default.conf:/etc/nginx/conf.d/default.conf
  # #            - ./app/code:/usr/share/nginx/html
  #         ports:
  #             - 8089:80
  #         networks:
  #             - galileo-network
  apptest:
    image: galileo/galileo-webapptest
    container_name: webapptest
    restart: on-failure
    volumes:
      #          -  ./app/nginx.conf:/etc/nginx/nginx.conf
      - ./app/default.conf:/etc/nginx/conf.d/default.conf
    #            - ./app/code:/usr/share/nginx/html
    ports:
      - 8099:80
    networks:
      - galileo-network
    #networks:
    #galileo-network:
    #ipam:
    #driver: default
    #config:
    #- subnet: 10.10.0.0/24

networks:
  galileo-network:
    external: true
    name: galileo-network
